export enum Platform {
  // Consoles de salon
  ATARI_2600 = 'ATARI_2600',
  ATARI_5200 = 'ATARI_5200',
  NINTENDO_NES = 'NINTENDO_NES',
  NINTENDO_SNES = 'NINTENDO_SNES',
  NINTENDO_64 = 'NINTENDO_64',
  NINTENDO_GAMECUBE = 'NINTENDO_GAMECUBE',
  NINTENDO_WII = 'NINTENDO_WII',
  NINTENDO_WII_U = 'NINTENDO_WII_U',
  NINTENDO_SWITCH = 'NINTENDO_SWITCH',
  SONY_PLAYSTATION_1 = 'SONY_PLAYSTATION_1',
  SONY_PLAYSTATION_2 = 'SONY_PLAYSTATION_2',
  SONY_PLAYSTATION_3 = 'SONY_PLAYSTATION_3',
  SONY_PLAYSTATION_4 = 'SONY_PLAYSTATION_4',
  SONY_PLAYSTATION_5 = 'SONY_PLAYSTATION_5',
  MICROSOFT_XBOX = 'MICROSOFT_XBOX',
  MICROSOFT_XBOX_360 = 'MICROSOFT_XBOX_360',
  MICROSOFT_XBOX_ONE = 'MICROSOFT_XBOX_ONE',
  MICROSOFT_XBOX_SERIES_X = 'MICROSOFT_XBOX_SERIES_X',
  MICROSOFT_XBOX_SERIES_S = 'MICROSOFT_XBOX_SERIES_S',
  SEGA_MASTER_SYSTEM = 'SEGA_MASTER_SYSTEM',
  SEGA_MEGA_DRIVE = 'SEGA_MEGA_DRIVE',
  SEGA_SATURN = 'SEGA_SATURN',
  SEGA_DREAMCAST = 'SEGA_DREAMCAST',

  // Consoles portables
  NINTENDO_GAME_BOY = 'NINTENDO_GAME_BOY',
  NINTENDO_GAME_BOY_COLOR = 'NINTENDO_GAME_BOY_COLOR',
  NINTENDO_GAME_BOY_ADVANCE = 'NINTENDO_GAME_BOY_ADVANCE',
  NINTENDO_DS = 'NINTENDO_DS',
  NINTENDO_3DS = 'NINTENDO_3DS',
  NINTENDO_GAME_AND_WATCH = 'NINTENDO_GAME_AND_WATCH',
  NINTENDO_SWITCH_LITE = 'NINTENDO_SWITCH_LITE',
  SONY_PSP = 'SONY_PSP',
  SONY_PS_VITA = 'SONY_PS_VITA',
  SEGA_GAME_GEAR = 'SEGA_GAME_GEAR',
  NEO_GEO_POCKET = 'NEO_GEO_POCKET',
  NEO_GEO_POCKET_COLOR = 'NEO_GEO_POCKET_COLOR',
  ATARI_LYNX = 'ATARI_LYNX',

  // PC et ordinateurs
  WINDOWS = 'WINDOWS',
  MACOS = 'MACOS',
  LINUX = 'LINUX',
  AMIGA = 'AMIGA',
  COMMODORE_64 = 'COMMODORE_64',
  MSX = 'MSX',
  ZX_SPECTRUM = 'ZX_SPECTRUM',
  DOS = 'DOS',

  // Smartphones et tablettes
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WINDOWS_PHONE = 'WINDOWS_PHONE',

  // Plates-formes VR
  OCULUS_RIFT = 'OCULUS_RIFT',
  META_QUEST = 'META_QUEST',
  HTC_VIVE = 'HTC_VIVE',
  PLAYSTATION_VR = 'PLAYSTATION_VR',
  VALVE_INDEX = 'VALVE_INDEX',
  GOOGLE_DAYDREAM = 'GOOGLE_DAYDREAM',
  SAMSUNG_GEAR_VR = 'SAMSUNG_GEAR_VR',

  // Consoles hybrides / alternatives
  STEAM_DECK = 'STEAM_DECK',
  PICO_8 = 'PICO_8',
  ANALOGUE_POCKET = 'ANALOGUE_POCKET',
  EVERCADE = 'EVERCADE',

  // Machines d'arcade
  ARCADE_CLASSIC = 'ARCADE_CLASSIC',
  NEO_GEO_MVS = 'NEO_GEO_MVS'
}
