export enum VideoGameGenre {
  // Jeux d'action
  ACTION = 'ACTION',
  ACTION_ADVENTURE = 'ACTION_ADVENTURE',
  BEAT_EM_UP = 'BEAT_EM_UP',
  HACK_AND_SLASH = 'HACK_AND_SLASH',
  SHOOT_EM_UP = 'SHOOT_EM_UP',
  RUN_AND_GUN = 'RUN_AND_GUN',
  FIGHTING = 'FIGHTING',
  PLATFORMER = 'PLATFORMER',
  STEALTH = 'STEALTH',
  SURVIVAL = 'SURVIVAL',

  // Jeux d'aventure
  VISUAL_NOVEL = 'VISUAL_NOVEL',
  NARRATIVE_DRIVEN = 'NARRATIVE_DRIVEN',
  POINT_AND_CLICK = 'POINT_AND_CLICK',
  INTERACTIVE_MOVIE = 'INTERACTIVE_MOVIE',

  // Jeux de rôle (RPG)
  JRPG = 'JRPG',
  WRPG = 'WRPG',
  TACTICAL_RPG = 'TACTICAL_RPG',
  MMORPG = 'MMORPG',
  ACTION_RPG = 'ACTION_RPG',
  ROGUELIKE = 'ROGUELIKE',
  DUNGEON_CRAWLER = 'DUNGEON_CRAWLER',

  // Jeux de stratégie
  RTS = 'RTS',
  TBS = 'TBS',
  TOWER_DEFENSE = 'TOWER_DEFENSE',
  FOUR_X = 'FOUR_X', // eXplore, eXpand, eXploit, eXterminate
  MOBA = 'MOBA',

  // Jeux de simulation
  LIFE_SIMULATION = 'LIFE_SIMULATION',
  MANAGEMENT_SIMULATION = 'MANAGEMENT_SIMULATION',
  SPORTS_SIMULATION = 'SPORTS_SIMULATION',
  FLIGHT_SIMULATION = 'FLIGHT_SIMULATION',
  FARMING_SIMULATION = 'FARMING_SIMULATION',
  MILITARY_SIMULATION = 'MILITARY_SIMULATION',

  // Jeux de sport et de course
  REALISTIC_SPORTS = 'REALISTIC_SPORTS',
  ARCADE_SPORTS = 'ARCADE_SPORTS',
  REALISTIC_RACING = 'REALISTIC_RACING',
  ARCADE_RACING = 'ARCADE_RACING',

  // Jeux de réflexion et puzzles
  PUZZLE = 'PUZZLE',
  WORD_GAME = 'WORD_GAME',
  ESCAPE_GAME = 'ESCAPE_GAME',

  // Jeux de tir
  FPS = 'FPS',
  TPS = 'TPS',
  HERO_SHOOTER = 'HERO_SHOOTER',
  BATTLE_ROYALE = 'BATTLE_ROYALE',

  // Jeux multijoueurs
  PARTY_GAME = 'PARTY_GAME',
  COOPERATIVE_GAME = 'COOPERATIVE_GAME',
  MASSIVELY_MULTIPLAYER = 'MASSIVELY_MULTIPLAYER',

  // Jeux indépendants
  INDIE = 'INDIE'
}
